
-- Nyra Service Tool :: schema v1
-- Postgres-first. bigint identity PKs, text+CHECK instead of enums, jsonb extension points.
-- Every business table carries tenant_id (application-enforced tenancy).

begin;

-- ---------------------------------------------------------------- tenant / org
create table if not exists tenant (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,
  name          text not null,
  settings      jsonb not null default '{}'::jsonb,
  license_plan  text not null default 'community',
  created_at    timestamptz not null default now()
);

create table if not exists org_unit (
  id          bigint generated by default as identity primary key,
  tenant_id   bigint not null references tenant(id) on delete cascade,
  kind        text not null check (kind in ('company','division','department','cost_center','location','region','site')),
  name        text not null,
  code        text,
  parent_id   bigint references org_unit(id) on delete set null,
  timezone    text not null default 'UTC',
  country     text,
  state       text,
  city        text,
  address     jsonb not null default '{}'::jsonb,
  active      boolean not null default true
);
create index if not exists org_unit_tenant_kind_idx on org_unit(tenant_id, kind);

create table if not exists business_calendar (
  id          bigint generated by default as identity primary key,
  tenant_id   bigint not null references tenant(id) on delete cascade,
  name        text not null,
  timezone    text not null default 'Asia/Kolkata',
  work_days   int[] not null default '{1,2,3,4,5}',      -- ISO weekday numbers
  work_start  time not null default '09:00',
  work_end    time not null default '18:00',
  holidays    jsonb not null default '[]'::jsonb,        -- ["2026-10-02", ...]
  active      boolean not null default true,
  unique (tenant_id, name)
);

-- ---------------------------------------------------------------- people
create table if not exists person (
  id              bigint generated by default as identity primary key,
  tenant_id       bigint not null references tenant(id) on delete cascade,
  party_type      text not null default 'employee'
                  check (party_type in ('employee','contractor','partner','customer','vendor_contact','system')),
  user_name       text,
  first_name      text,
  last_name       text,
  display_name    text not null,
  email           text,
  personal_email  text,
  phone           text,
  mobile          text,
  caller_id       text,                                  -- ANI / DID matched on inbound call
  job_title       text,
  employee_id     text,
  department_id   bigint references org_unit(id) on delete set null,
  company_id      bigint references org_unit(id) on delete set null,
  location_id     bigint references org_unit(id) on delete set null,
  cost_center     text,
  grade           text,
  worker_type     text check (worker_type in ('full_time','part_time','contract','intern','vendor','unknown')),
  manager_id      bigint references person(id) on delete set null,
  roles           text[] not null default '{}',          -- end_user, agent_l1, agent_l2, team_lead, admin, service_owner
  access_level    text not null default 'standard' check (access_level in ('restricted','standard','elevated','privileged')),
  team_id         bigint,                                -- primary assignment group (FK added after team table)
  is_vip          boolean not null default false,
  vip_reason      text,
  language        text not null default 'en',
  timezone        text not null default 'Asia/Kolkata',
  address         jsonb not null default '{}'::jsonb,
  consents        jsonb not null default '{}'::jsonb,
  hire_date       date,
  last_login_at   timestamptz,
  is_active       boolean not null default true,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists person_tenant_email_idx on person(tenant_id, lower(email));
create index if not exists person_tenant_active_idx on person(tenant_id, is_active);
create index if not exists person_manager_idx on person(manager_id);

-- ---------------------------------------------------------------- teams (assignment groups)
create table if not exists team (
  id               bigint generated by default as identity primary key,
  tenant_id        bigint not null references tenant(id) on delete cascade,
  name             text not null,
  code             text,
  tier             text check (tier in ('l1','l2','l3','l4','vendor','governance','business')),
  domain           text not null default 'it' check (domain in ('it','hr','finance','facilities','legal','security','clinical','manufacturing','retail','other')),
  email            text,                                 -- distribution list address: group mail fan-out
  mailbox_mode     text not null default 'relay' check (mailbox_mode in ('relay','app_expanded')),
  shared_mailbox   text,
  manager_id       bigint references person(id) on delete set null,
  escalation_team_id bigint references team(id) on delete set null,
  calendar_id      bigint references business_calendar(id) on delete set null,
  default_sla_policy_id bigint,
  skills           text[] not null default '{}',
  description      text,
  active           boolean not null default true,
  created_at       timestamptz not null default now()
);
create index if not exists team_tenant_domain_idx on team(tenant_id, domain, tier);

alter table person
  add constraint person_team_fk foreign key (team_id) references team(id) on delete set null;

create table if not exists team_member (
  id        bigint generated by default as identity primary key,
  team_id   bigint not null references team(id) on delete cascade,
  person_id bigint not null references person(id) on delete cascade,
  team_role text not null default 'member' check (team_role in ('member','lead','manager','backup','on_call')),
  is_primary boolean not null default true,
  capacity  int,
  unique (team_id, person_id)
);

-- ---------------------------------------------------------------- sla
create table if not exists sla_policy (
  id                  bigint generated by default as identity primary key,
  tenant_id           bigint not null references tenant(id) on delete cascade,
  name                text not null,
  applies_to          text not null default 'incident' check (applies_to in ('incident','problem','change','request','task','any')),
  match_priority      int[],                             -- e.g. {1,2}
  match_service_id    bigint,
  match_team_id       bigint,
  response_minutes    int,
  resolution_minutes  int,
  update_interval_minutes int,
  use_business_hours  boolean not null default true,
  calendar_id         bigint references business_calendar(id) on delete set null,
  pause_states        text[] not null default '{on_hold}',
  at_risk_percent     int not null default 75,
  active              boolean not null default true,
  unique (tenant_id, name)
);

-- ---------------------------------------------------------------- taxonomy / services / ci
create table if not exists taxonomy (
  id            bigint generated by default as identity primary key,
  tenant_id     bigint not null references tenant(id) on delete cascade,
  kind          text not null check (kind in ('category','subcategory','sub_subcategory')),
  domain        text not null default 'it',
  name          text not null,
  parent_id     bigint references taxonomy(id) on delete cascade,
  default_team_id bigint references team(id) on delete set null,
  default_priority int,
  keywords      text[] not null default '{}',            -- feeds the AI classifier
  active        boolean not null default true
);
create index if not exists taxonomy_tenant_parent_idx on taxonomy(tenant_id, parent_id);

create table if not exists service (
  id            bigint generated by default as identity primary key,
  tenant_id     bigint not null references tenant(id) on delete cascade,
  name          text not null,
  service_type  text not null default 'business' check (service_type in ('business','technical','application','offering')),
  domain        text not null default 'it',
  owner_id      bigint references person(id) on delete set null,
  criticality   text not null default 'medium' check (criticality in ('critical','high','medium','low')),
  support_team_id bigint references team(id) on delete set null,
  sla_policy_id bigint references sla_policy(id) on delete set null,
  status        text not null default 'live' check (status in ('planned','live','deprecated','retired')),
  description   text,
  active        boolean not null default true
);

create table if not exists ci (
  id            bigint generated by default as identity primary key,
  tenant_id     bigint not null references tenant(id) on delete cascade,
  name          text not null,
  ci_class      text not null,                           -- server, application, database, network_device, service, cloud_resource...
  sys_class     text not null default 'cmdb_ci',
  environment   text check (environment in ('prod','staging','test','dev','dr','unknown')),
  operational_status text not null default 'operational'
                check (operational_status in ('operational','non_operational','repair_in_progress','dr_standby','retired')),
  criticality   text not null default 'medium',
  owner_id      bigint references person(id) on delete set null,
  support_team_id bigint references team(id) on delete set null,
  location_id   bigint references org_unit(id) on delete set null,
  parent_id     bigint references ci(id) on delete set null,
  discovered    boolean not null default false,
  attributes    jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);
create index if not exists ci_tenant_class_idx on ci(tenant_id, ci_class);

-- ---------------------------------------------------------------- numbering
create table if not exists numbering_sequence (
  id        bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id) on delete cascade,
  key       text not null,                               -- incident, problem, change, request, ritm, task, kb
  prefix    text not null,
  next_value bigint not null default 1,
  padding   int not null default 7,
  unique (tenant_id, key)
);

-- ---------------------------------------------------------------- records (all ticket types)
create table if not exists record (
  id                 bigint generated by default as identity primary key,
  tenant_id          bigint not null references tenant(id) on delete cascade,
  number             text not null,
  type               text not null check (type in ('incident','problem','change','request','ritm','task','problem_task','change_task','catalog_task')),
  parent_id          bigint references record(id) on delete set null,
  root_id            bigint references record(id) on delete set null,

  short_description  text not null,
  description        text,
  state              text not null default 'new',
  state_reason       text,

  opened_by          bigint references person(id) on delete set null,
  opened_at          timestamptz not null default now(),
  caller_id          bigint references person(id) on delete set null,
  channel            text not null default 'portal' check (channel in ('portal','email','phone','chat','walk_up','api','monitoring','agent','teams','whatsapp','system')),
  contact_type       text,

  assignment_group_id bigint references team(id) on delete set null,
  assignee_id        bigint references person(id) on delete set null,
  created_by         bigint references person(id) on delete set null,
  updated_by         bigint references person(id) on delete set null,

  priority           int not null default 4 check (priority between 1 and 5),
  urgency            int not null default 3 check (urgency between 1 and 3),
  impact             int not null default 3 check (impact between 1 and 3),
  severity           text,
  priority_override_reason text,

  category_id        bigint references taxonomy(id) on delete set null,
  subcategory_id     bigint references taxonomy(id) on delete set null,
  service_id         bigint references service(id) on delete set null,
  ci_id              bigint references ci(id) on delete set null,
  location_id        bigint references org_unit(id) on delete set null,
  department_id      bigint references org_unit(id) on delete set null,
  company_id         bigint references org_unit(id) on delete set null,

  major_incident     boolean not null default false,
  escalation         boolean not null default false,
  escalation_reason  text,
  quality_miss       boolean not null default false,
  security_flag      boolean not null default false,
  regulatory_flag    boolean not null default false,
  on_hold_reason     text,
  reopen_count       int not null default 0,
  reassignment_count int not null default 0,
  first_call_resolution boolean,

  workaround         text,
  resolution_notes   text,
  resolution_code    text,
  root_cause_code    text,
  close_code         text,

  response_at        timestamptz,
  response_due_at    timestamptz,
  response_met       boolean,
  resolve_due_at     timestamptz,
  resolved_at        timestamptz,
  resolution_met     boolean,
  closed_at          timestamptz,
  due_at             timestamptz,
  sla_state          text not null default 'ok' check (sla_state in ('ok','at_risk','breached','paused')),
  sla_policy_id      bigint references sla_policy(id) on delete set null,

  followup           jsonb not null default '{"enabled": false, "interval_hours": 24, "max_count": 3, "sent_count": 0, "no_response_action": "auto_close"}'::jsonb,
  autoclose          jsonb not null default '{"enabled": true, "after_followups": 3, "business_days_to_close": 5, "reopen_window_hours": 72}'::jsonb,
  ai                 jsonb not null default '{}'::jsonb,
  ext                jsonb not null default '{}'::jsonb,
  tags               text[] not null default '{}',

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  deleted_at         timestamptz,
  unique (tenant_id, number)
);
create index if not exists record_tenant_type_state_idx on record(tenant_id, type, state);
create index if not exists record_assignee_idx on record(assignee_id, state);
create index if not exists record_group_idx on record(assignment_group_id, state);
create index if not exists record_caller_idx on record(caller_id);
create index if not exists record_parent_idx on record(parent_id);
create index if not exists record_search_idx on record using gin (to_tsvector('english', coalesce(short_description,'') || ' ' || coalesce(description,'')));
create index if not exists record_number_idx on record(number);

create table if not exists record_comment (
  id            bigint generated by default as identity primary key,
  tenant_id     bigint not null references tenant(id) on delete cascade,
  record_id     bigint not null references record(id) on delete cascade,
  author_id     bigint references person(id) on delete set null,
  kind          text not null check (kind in ('work_note','public_comment','system','email_in','email_out')),
  body          text not null,
  source        text not null default 'agent',
  is_internal   boolean not null default true,
  email_message_id text,
  created_at    timestamptz not null default now(),
  edited_at     timestamptz
);
create index if not exists record_comment_record_idx on record_comment(record_id, created_at);

create table if not exists record_relationship (
  id          bigint generated by default as identity primary key,
  tenant_id   bigint not null references tenant(id) on delete cascade,
  record_id   bigint not null references record(id) on delete cascade,
  related_id  bigint not null references record(id) on delete cascade,
  relation    text not null check (relation in ('relates_to','duplicate_of','caused_by','blocks','blocked_by','child_of','parent_of','resolved_by')),
  created_at  timestamptz not null default now(),
  unique (record_id, related_id, relation)
);

create table if not exists attachment (
  id          bigint generated by default as identity primary key,
  tenant_id   bigint not null references tenant(id) on delete cascade,
  record_id   bigint references record(id) on delete cascade,
  article_id  bigint,
  filename    text not null,
  content_type text,
  size_bytes  bigint,
  driver      text not null default 'local' check (driver in ('local','supabase','s3','minio')),
  storage_key text not null,
  sha256      text,
  uploaded_by bigint references person(id) on delete set null,
  created_at  timestamptz not null default now()
);

create table if not exists audit_log (
  id          bigint generated by default as identity primary key,
  tenant_id   bigint not null references tenant(id) on delete cascade,
  entity_type text not null,
  entity_id   bigint,
  action      text not null,
  field       text,
  old_value   text,
  new_value   text,
  actor_id    bigint references person(id) on delete set null,
  actor_type  text not null default 'user' check (actor_type in ('user','system','ai','integration','api')),
  channel     text,
  ip          inet,
  user_agent  text,
  at          timestamptz not null default now()
);
create index if not exists audit_entity_idx on audit_log(entity_type, entity_id, at desc);

-- ---------------------------------------------------------------- knowledge
create table if not exists kb_article (
  id            bigint generated by default as identity primary key,
  tenant_id     bigint not null references tenant(id) on delete cascade,
  number        text not null,
  title         text not null,
  summary       text,
  body          text not null,
  state         text not null default 'draft' check (state in ('draft','in_review','published','retired')),
  visibility    text not null default 'portal' check (visibility in ('internal','portal','public')),
  owner_id      bigint references person(id) on delete set null,
  category_id   bigint references taxonomy(id) on delete set null,
  service_id    bigint references service(id) on delete set null,
  tags          text[] not null default '{}',
  version       int not null default 1,
  hit_count     int not null default 0,
  helpful_count int not null default 0,
  not_helpful_count int not null default 0,
  review_due_at date,
  published_at  timestamptz,
  created_by    bigint references person(id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (tenant_id, number)
);
create index if not exists kb_search_idx on kb_article using gin (to_tsvector('english', title || ' ' || coalesce(summary,'') || ' ' || body));

create table if not exists kb_feedback (
  id         bigint generated by default as identity primary key,
  article_id bigint not null references kb_article(id) on delete cascade,
  person_id  bigint references person(id) on delete set null,
  helpful    boolean not null,
  comment    text,
  created_at timestamptz not null default now()
);

create table if not exists csat_survey (
  id           bigint generated by default as identity primary key,
  tenant_id    bigint not null references tenant(id) on delete cascade,
  record_id    bigint not null references record(id) on delete cascade,
  person_id    bigint references person(id) on delete set null,
  score        int check (score between 1 and 5),
  comment      text,
  sent_at      timestamptz,
  responded_at timestamptz,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- notifications
create table if not exists notification_template (
  id         bigint generated by default as identity primary key,
  tenant_id  bigint not null references tenant(id) on delete cascade,
  code       text not null,
  event      text not null,
  channel    text not null default 'email' check (channel in ('email','in_app','chat','sms','push')),
  locale     text not null default 'en',
  subject    text not null,
  body       text not null,
  version    int not null default 1,
  active     boolean not null default true,
  unique (tenant_id, code, locale, version)
);

create table if not exists notification_audience (
  id             bigint generated by default as identity primary key,
  tenant_id      bigint not null references tenant(id) on delete cascade,
  code           text not null,
  name           text not null,
  audience_type  text not null check (audience_type in ('person','team_dl','shared_mailbox','distribution_list','org_slice','role','on_call','watchlist','case_team','external','system')),
  expression     jsonb not null default '{}'::jsonb,    -- {kind:'location', id:12} | {kind:'department', id:4}
  expansion_mode text not null default 'relay' check (expansion_mode in ('relay','app_expanded')),
  privacy_class  text not null default 'internal' check (privacy_class in ('internal','external','restricted')),
  active         boolean not null default true,
  unique (tenant_id, code)
);

create table if not exists notification_send_log (
  id              bigint generated by default as identity primary key,
  tenant_id       bigint not null references tenant(id) on delete cascade,
  record_id       bigint references record(id) on delete cascade,
  template_code   text,
  template_version int,
  audience_code   text,
  recipients_count int not null default 0,
  recipients      jsonb not null default '[]'::jsonb,
  delivery_state  text not null default 'queued'
                  check (delivery_state in ('queued','sent','delivered','bounced','complained','opened','clicked','actioned','suppressed','failed')),
  proof_class     text not null default 'informational' check (proof_class in ('informational','transactional','regulatory_evidence')),
  initiated_by    bigint references person(id) on delete set null,
  initiated_by_type text not null default 'system' check (initiated_by_type in ('user','system','ai','rule')),
  message_id      text,
  error           text,
  created_at      timestamptz not null default now()
);
create index if not exists send_log_record_idx on notification_send_log(record_id, created_at desc);

-- ---------------------------------------------------------------- views
create table if not exists saved_view (
  id        bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id) on delete cascade,
  name      text not null,
  entity    text not null default 'record',
  owner_id  bigint references person(id) on delete set null,
  filters   jsonb not null default '{}'::jsonb,
  columns   jsonb not null default '[]'::jsonb,
  shared    boolean not null default false,
  sort      text,
  created_at timestamptz not null default now()
);

commit;
